### ISSUE TITLE
No module named pygatt

### ISSUE THREAD

**Issue by TomasHubelbauer** [kariudo/onewheel-bluetooth#2]
Hey, sorry, this is a Python noob question and I don't like to bother you with it, but it is something that could maybe be added in the README:

I am on a fresh Ubuntu 18.04 installation, have Python 3 out-of-the-box and when I run the script as per the README, I get *ModuleNotFoundError: No module named 'pygatt'*.

I figured I needed to install the `pygatt` package using PIP, so installed PIP using `sudo apt-get install python3-pip` and then ran `pip install pygatt`. However, this didn't help, the same invocation ends with the same result, even though I believe the `pygatt` package should be installed now.

Do you know what gives?

**Comment by TomasHubelbauer** [comment]
I've since found out this module doesn't support Bluetooth on Windows and have ported the code over to Web Bluetooth using JavaScript instead.

**Comment by kariudo** [comment]
As an FYI, since pygatt is pretty dead in the water, I rewrote the project with `bleak` as a library. Which should be cross-platform friendly.
